### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by Znpos901** [TheValkyrja/VertexClaudeProxy#2]
1：readme里写的多个project_id的间隔符不大准确，实质是英文逗号+空格，少了空格不行（我不确定这算不算吹毛求疵，但的确存在）
2：不能读图，报错500，同网络环境下使用sdk的原项目是可以的，win平台，python启动

**Comment by TheValkyrja** [comment]
1.是的，但是我现在懒得改，等我把一些别的功能弄好就弄
2.你使用的客户端是什么，我使用的Librechat测试是正常的

**Comment by Znpos901** [comment]
酒馆和chatbox都测试过，都报错

**Comment by Znpos901** [comment]
具体流程：python启动项目，本地酒馆连接聊天正常，读图正常200，然后使用chatbox读图，报错500，再次使用酒馆测试，继续报错500，重启项目则酒馆能够正常读图，直到再次使用chatbox尝试，再次报错

**Comment by TheValkyrja** [comment]
> 具体流程：python启动项目，本地酒馆连接聊天正常，读图正常200，然后使用chatbox读图，报错500，再次使用酒馆测试，继续报错500，重启项目则酒馆能够正常读图，直到再次使用chatbox尝试，再次报错

两个都是读图错误对吧？
提供一下你的chatbox配置细节，我测试之后就回复你。

**Comment by TheValkyrja** [comment]
> 具体流程：python启动项目，本地酒馆连接聊天正常，读图正常200，然后使用chatbox读图，报错500，再次使用酒馆测试，继续报错500，重启项目则酒馆能够正常读图，直到再次使用chatbox尝试，再次报错

我尝试了一下，没能在网页版chatbox中简单复现你的读图问题。你使用的是我现在最新的代码吗？先前的代码在处理错误的函数部分有几个变量填错了，会引发500错误（按照你的fork中的修改不能解决），现在已经修复了。
如果你能稳定复现问题，请你把你的chatbox客户端、系统、设置（隐去敏感信息）、发送的具体图片（若不便，提供图片格式和体积）列出，看看我能不能复现。

**Comment by Znpos901** [comment]
> > 具体流程：python启动项目，本地酒馆连接聊天正常，读图正常200，然后使用chatbox读图，报错500，再次使用酒馆测试，继续报错500，重启项目则酒馆能够正常读图，直到使用chatbox尝试，再次报错
> 
> 我尝试一下，没能在网页版聊天框中简单地复现你的读图问题。你使用的是我现在最新的代码吗？前面的代码在处理错误的函数部分有几个变量填错了，会引发500错误（按照你的fork中的修改不能解决），现在已经修复了。 如果你能稳定复现问题，请你把你的聊天室客户端、系统、设置（隐去敏感信息）、发送的具体图片（若不便，提供图片格式和体积）现已上市，看看我无法复现。

我用的确实是你的原始代码，今天回复的时候刚扒下来的，不是我自己fork的分支，那只是前两天随手弄的，确认无法传图的问题在我这可以稳定复现，具体图片在这，只是随手找的一个游戏截图，所使用的聊天客户端分别为SillyTavern 1.12.3 'release' (a410c633)和chatbox1.3.17，均使用claude3.5，本地127.0.0.1:5000无改动，系统是win10专业版22H2，酒馆设置中打开了压缩系统信息和发送内联图像，新项目是多账号模式启动，在新项目报错的情况下，切换旧项目正常传图，期间端口无重复占用
![ryujinx_capture_2022-11-24_23-38-57](https://github.com/user-attachments/assets/ddbafea1-60a2-4035-90bf-7acfc72a4495)

**Comment by TheValkyrja** [comment]
> > > 具体流程：python启动项目，本地酒馆连接聊天正常，读图正常200，然后使用chatbox读图，报错500，再次使用酒馆测试，继续报错500，重启项目则酒馆能够正常读图，直到使用chatbox尝试，再次报错
> > 
> > 
> > 我尝试一下，没能在网页版聊天框中简单地复现你的读图问题。你使用的是我现在最新的代码吗？前面的代码在处理错误的函数部分有几个变量填错了，会引发500错误（按照你的fork中的修改不能解决），现在已经修复了。 如果你能稳定复现问题，请你把你的聊天室客户端、系统、设置（隐去敏感信息）、发送的具体图片（若不便，提供图片格式和体积）现已上市，看看我无法复现。
> 
> 我用的确实是你的原始代码，今天回复的时候刚扒下来的，不是我自己fork的分支，那只是前两天随手弄的，确认无法传图的问题在我这可以稳定复现，具体图片在这，只是随手找的一个游戏截图，所使用的聊天客户端分别为SillyTavern 1.12.3 'release' (a410c633)和chatbox1.3.17，均使用claude3.5，本地127.0.0.1:5000无改动，系统是win10专业版22H2，酒馆设置中打开了压缩系统信息和发送内联图像，新项目是多账号模式启动，在新项目报错的情况下，切换旧项目正常传图，期间端口无重复占用 ![ryujinx_capture_2022-11-24_23-38-57](https://private-user-images.githubusercontent.com/115646234/352851016-ddbafea1-60a2-4035-90bf-7acfc72a4495.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjAxMDcsIm5iZiI6MTcyMjIxOTgwNywicGF0aCI6Ii8xMTU2NDYyMzQvMzUyODUxMDE2LWRkYmFmZWExLTYwYTItNDAzNS05MGJmLTdhY2ZjNzJhNDQ5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwMjIzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGM3NDI3NzQ2MzVmZmI3YTc4ZDY2ZGQzYjAyOWY4Nzg1NWYyZDVjMGE0OWM1NjI2NGRkNjRlZGNlM2I5OTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f6BEqQkM-awGmt47heBDpmRqXpRV3vKVrcSxfl-lNIo)

我尝试了使用你这个图片，确实可以稳定复现，但是我没有遇到”同时影响其他线程“的问题，可能是触发条件比较严苛。
我简单测试了一下，目前猜测是图片体积导致的，应该是对于大图片的base64编码，官方sdk有分片机制之类，直接使用http在图片在几百k的时候可以正常使用。

感觉这个问题不太好处理，看看最近把sdk项目也维护起来，最麻烦的报错功能已经写好了，负载均衡直接搬进去就行。

**Comment by TheValkyrja** [comment]
> > > 具体流程：python启动项目，本地酒馆连接聊天正常，读图正常200，然后使用chatbox读图，报错500，再次使用酒馆测试，继续报错500，重启项目则酒馆能够正常读图，直到使用chatbox尝试，再次报错
> > 
> > 
> > 我尝试一下，没能在网页版聊天框中简单地复现你的读图问题。你使用的是我现在最新的代码吗？前面的代码在处理错误的函数部分有几个变量填错了，会引发500错误（按照你的fork中的修改不能解决），现在已经修复了。 如果你能稳定复现问题，请你把你的聊天室客户端、系统、设置（隐去敏感信息）、发送的具体图片（若不便，提供图片格式和体积）现已上市，看看我无法复现。
> 
> 我用的确实是你的原始代码，今天回复的时候刚扒下来的，不是我自己fork的分支，那只是前两天随手弄的，确认无法传图的问题在我这可以稳定复现，具体图片在这，只是随手找的一个游戏截图，所使用的聊天客户端分别为SillyTavern 1.12.3 'release' (a410c633)和chatbox1.3.17，均使用claude3.5，本地127.0.0.1:5000无改动，系统是win10专业版22H2，酒馆设置中打开了压缩系统信息和发送内联图像，新项目是多账号模式启动，在新项目报错的情况下，切换旧项目正常传图，期间端口无重复占用 ![ryujinx_capture_2022-11-24_23-38-57](https://private-user-images.githubusercontent.com/115646234/352851016-ddbafea1-60a2-4035-90bf-7acfc72a4495.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTk1OTEsIm5iZiI6MTcyMjMxOTI5MSwicGF0aCI6Ii8xMTU2NDYyMzQvMzUyODUxMDE2LWRkYmFmZWExLTYwYTItNDAzNS05MGJmLTdhY2ZjNzJhNDQ5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwNjAxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmM4NTYxYWViZGY4YTdkMDBmNGJmZjM3NWEzNmYzMjA2YzliNzA0MjdmMWY3Mzg1N2ZjMDI2ZDRjN2JhZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LIuiGoLYukTK4MXRIM7j41bnoMBPYcPNhYWRqemiljE)

你好， 我检查到原因了，问题所在是我现在的代码算法有严重的性能损耗，当我把请求超时时长设置成30秒后，就可以正常收到回复了。

我已经设计了新的逻辑流程，近日重构好了之后会更新。我会优先维护SDK项目的功能和逻辑更新。

**Comment by TheValkyrja** [comment]
最新的commit已经解决了对于本项目的大图片报错问题。对于你的图片，在我的实例中，使用claude 3.5 sonnet需要大约17-20秒来得到第一次响应。请测试这个版本。对于使用claude 3 opus的情形我未进行测试，如果仍然存在这个问题，请让我知道。

**Comment by Znpos901** [comment]
实测已解决，opus一样可用，可能是个人网络状况或服务器负载问题导致的差异，30s在测试2.5mb以上较大图片的时候仍然会超时，手动修改超时时长后可正常回复，如有后续更新，建议将此类因超时导致的报错与其它未知原因的报错区分开来

**Comment by TheValkyrja** [comment]
> 实测已解决，opus一样可用，可能是个人网络状况或服务器负载问题导致的差异，30s在测试2.5mb以上较大图片的时候仍然会超时，手动修改超时时长后可正常回复，如有后续更新，建议将此类因超时导致的报错与其它未知原因的报错区分开来

从设计的角度考虑感觉没必要，它实际上不是Anthropic引发的错误。可以考虑的是根据请求体大小动态设置超时时间以避免引发此问题。或者干脆直接加到120.谢谢你的测试。
